// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignalR_Chat.Data.Context;

namespace SignalR_Chat.Data.Migrations
{
    [DbContext(typeof(ChatContext))]
    [Migration("20210301124448_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("SignalR_Chat.Models.Entities.UserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserType");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "System"
                        },
                        new
                        {
                            Id = 1,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("SignalR_Chat.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserReceiverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserSenderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserReceiverId");

                    b.HasIndex("UserSenderId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("SignalR_Chat.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("UserTypeId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1992, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sistema",
                            UserTypeId = 2
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1995, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mathieu",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1998, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "José",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1994, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jurassic Park",
                            UserTypeId = 1
                        });
                });

            modelBuilder.Entity("SignalR_Chat.Models.Message", b =>
                {
                    b.HasOne("SignalR_Chat.Models.User", "UserReceiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("UserReceiverId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("SignalR_Chat.Models.User", "UserSender")
                        .WithMany("SendedMessages")
                        .HasForeignKey("UserSenderId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("UserReceiver");

                    b.Navigation("UserSender");
                });

            modelBuilder.Entity("SignalR_Chat.Models.User", b =>
                {
                    b.HasOne("SignalR_Chat.Models.Entities.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("SignalR_Chat.Models.Entities.UserType", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SignalR_Chat.Models.User", b =>
                {
                    b.Navigation("ReceivedMessages");

                    b.Navigation("SendedMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
